eureka:
  client:
      instance:
        hostname: localhost
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
  security-service:
      endpoints:
        endpoint:
          uri: http://SECURITY-SERVICE/api/v1/auth
